matrix:
  RUBY_VERSION:
    - 2.3
    - 2.2

build:
  image: armhfbuild/alpine:3.2
  commands:
    - apk add --update git
    - git clone --single-branch https://github.com/docker-library/ruby upstream
    - cd upstream; sed -i 's/FROM buildpack-deps/FROM armhfbuild\/buildpack\-deps/' **/Dockerfile

publish:
  docker:
    image: armhfplugins/drone-docker:docker-caching
    file: upstream/$$RUBY_VERSION/Dockerfile
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/ruby
    tag:
      - "2.3.0"
      - "2.3"
      - "2"
      - "latest"
    storage_driver: overlay
    when:
      matrix:
        RUBY_VERSION: 2.3

publish:
  docker:
    image: armhfplugins/drone-docker:docker-caching
    file: upstream/$$RUBY_VERSION/Dockerfile
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/ruby
    tag:
      - "2.2.4"
      - "2.2"
    storage_driver: overlay
    when:
      matrix:
        RUBY_VERSION: 2.2

cache:
  mount:
    - /drone/docker
