matrix:
  VERSION:
    - "2.3.0"

build:
  image: armhfbuild/buildpack-deps:jessie-scm
  commands:
    - git clone --single-branch https://github.com/docker-library/ruby upstream
    - sed -i 's/FROM buildpack-deps/FROM armhfbuild\/buildpack-deps/' upstream/*/Dockerfile

publish:
  docker_version:
    image: armhfplugins/drone-docker:docker-caching
    context: upstream
    file: upstream/$${VERSION:0:3}/Dockerfile
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/ruby
    tag:
      - "$$VERSION"
      - "$${VERSION:0:3}"
      - "$${VERSION:0:1}"

  docker_latest:
    image: armhfplugins/drone-docker:docker-caching
    context: upstream
    file: upstream/$${VERSION:0:3}/Dockerfile
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/ruby
    tag: latest
    when:
      matrix:
        VERSION: "2.3.0"

cache:
  mount:
    - /drone/docker

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
